name: Build and Upload Release Assets

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for uploading release assets

    steps:
    - name: Dump GitHub event context
      run: echo "${{ toJSON(github.event) }}"

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.release.tag_name }} # Checkout the code at the release tag

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build for macOS
      run: bun run build:mac

    - name: Build for Linux
      run: bun run build:linux

    - name: Build for Windows
      run: bun run build:windows

    - name: Upload macOS Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/jira-parent-updater-mac
        asset_name: jira-parent-updater-mac
        asset_content_type: application/octet-stream

    - name: Upload Linux Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/jira-parent-updater-linux
        asset_name: jira-parent-updater-linux
        asset_content_type: application/octet-stream

    - name: Upload Windows Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/jira-parent-updater-win.exe
        asset_name: jira-parent-updater-win.exe
        asset_content_type: application/octet-stream 