name: Release

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'The new version to release'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: v${{ github.event.inputs.new_version }} # Checkout the specific tag passed from the bump-version workflow

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build for macOS
      run: bun run build:mac

    - name: Build for Linux
      run: bun run build:linux

    - name: Build for Windows
      run: bun run build:windows

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.new_version }}
        release_name: Release v${{ github.event.inputs.new_version }}
        draft: false
        prerelease: false

    - name: Upload macOS Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/jira-parent-updater-mac
        asset_name: jira-parent-updater-mac
        asset_content_type: application/octet-stream

    - name: Upload Linux Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/jira-parent-updater-linux
        asset_name: jira-parent-updater-linux
        asset_content_type: application/octet-stream

    - name: Upload Windows Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/jira-parent-updater-win.exe
        asset_name: jira-parent-updater-win.exe
        asset_content_type: application/octet-stream 