name: Release

on:
  pull_request:
    types: [closed]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: '0' # Required for semver-release-action

    - name: Semantic Release
      id: semver
      uses: K-Phoen/semver-release-action@master
      with:
        release_branch: main
        release_strategy: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Tagged Code
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.semver.outputs.tag }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Build for macOS
      run: bun run build:mac

    - name: Build for Linux
      run: bun run build:linux

    - name: Build for Windows
      run: bun run build:windows

    - name: Upload macOS Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/jira-parent-updater-mac
        asset_name: jira-parent-updater-mac
        asset_content_type: application/octet-stream

    - name: Upload Linux Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/jira-parent-updater-linux
        asset_name: jira-parent-updater-linux
        asset_content_type: application/octet-stream

    - name: Upload Windows Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./bin/jira-parent-updater-win.exe
        asset_name: jira-parent-updater-win.exe
        asset_content_type: application/octet-stream 