name: Semantic Version Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    permissions:
      contents: write # Needed for creating tags and releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: '0' # Required for semver-release-action

    - name: Semantic Release
      id: semver
      uses: K-Phoen/semver-release-action@master
      with:
        release_branch: main
        release_strategy: release # This will create a GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use default GITHUB_TOKEN for creating releases

    # Removed redundant build and upload steps from this workflow.
    # The build and upload will be handled by the 'build-and-upload.yml' workflow,
    # which is triggered by the 'release: published' event. 